### ISSUE TITLE
Extract images from RAW NAND

### ISSUE THREAD

**Issue by iDoka** [conchyliculture/Yand#11]
I dumped NAND image with command:
```
yand_cli.py --page_size 2048,128 --pages_per_block 64 --number_of_blocks 2048 --read --file TC58NVG1S3HTA00.bin
```

Now I would to use `binwalk` to extract filesystems and others deliverables.
How I can extract straight image from RAW NAND image? (I mean cut ECC part).

**Comment by conchyliculture** [comment]
This is for you to figure out =)
since a NAND just stores blocks, any structure on top of that is up to whatever chip it's connected to to decide. It might be that the last 128 bytes  (OOB) of each page is used for ECC, and you just have to trim these for every page. Maybe not

You can try to use the visialisation tool at [https://github.com/conchyliculture/Yand/blob/master/TOOLS.md](https://github.com/conchyliculture/Yand/blob/master/TOOLS.md) to figure out the structure.

Can you confirm #10 ca be closed?

**Comment by iDoka** [comment]
It is indeed hard to guess NAND inner structure.
What I know at this point:

1) from RK3308 TRM: 

- 16bit/1KB BCH/ECC: support 16bit BCH/ECC, which can detect and correct up to 16 error bits in every 1K bytes data and 4 bytes meta-data
- The BCH Encoder is responsible for encoding data to be written into NAND Flash device. The encoded length is 1056 bytes, in which the data length is 1024 bytes, system information (Meta-data) is 4 bytes, BCH code is 28 bytes.
- BCHCTL[16] determines whether codeword size for page data is 1024 bytes or 512 bytes

2) from binwalk I see that header is not aligned on page size:

```
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
126096        0x1EC90         CRC32 polynomial table, little endian
404624        0x62C90         CRC32 polynomial table, little endian
683152        0xA6C90         CRC32 polynomial table, little endian
961680        0xEAC90         CRC32 polynomial table, little endian
1240208       0x12EC90        CRC32 polynomial table, little endian
1518736       0x172C90        CRC32 polynomial table, little endian
2400016       0x249F10        CRC32 polynomial table, little endian
2434832       0x252710        CRC32 polynomial table, little endian
2469648       0x25AF10        CRC32 polynomial table, little endian
2504464       0x263710        CRC32 polynomial table, little endian
2785312       0x2A8020        Linux EXT filesystem, blocks count: 83228, image size: 85225472, rev 0.0, ext2 filesystem data (mounted or unclean), UUID=f1cab0c0-5b73-44c0-851d-08fda1c3a1c3, volume name "userdata"
88016546      0x53F06A2       Linux EXT filesystem, blocks count: 83228, image size: 85225472, rev 0.0, ext2 filesystem data (mounted or unclean), UUID=f1cab0c0-5b73-44c0-851d-08fda1c3a1c3, volume name "userdata"
186046478     0xB16D80E       Zlib compressed data, best compression
193122647     0xB82D157       Zlib compressed data, best compression
195010338     0xB9F9F22       Linux EXT filesystem, blocks count: 83228, image size: 85225472, rev 0.0, ext2 filesystem data (mounted or unclean), UUID=f1cab0c0-5b73-44c0-851d-08fda1c3a1c3, volume name "userdata"


```

**Comment by iDoka** [comment]
I think this issue not directly related to `Yand` and might be closed.

**Comment by conchyliculture** [comment]
Good luck with your research =)
